name: Deploy Mainnet API

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy_mainnet:
    name: Deploy Mainnet API
    uses: ./.github/workflows/deploy-api.yml
    with:
      env: "mainnet"
    secrets:
      aws_access_key_id: ${{ secrets['MAINNET_MARKET_MAP_UPDATER_AWS_ACCESS_KEY_ID'] }}
      aws_secret_access_key: ${{ secrets['MAINNET_MARKET_MAP_UPDATER_AWS_SECRET_ACCESS_KEY'] }}
