name: Deploy Staging API

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy_staging:
    name: Deploy Staging API
    uses: ./.github/workflows/deploy-api.yml
    with:
      env: "staging"
    secrets:
      aws_access_key_id: ${{ secrets['STAGING_MARKET_MAP_UPDATER_AWS_ACCESS_KEY_ID'] }}
      aws_secret_access_key: ${{ secrets['STAGING_MARKET_MAP_UPDATER_AWS_SECRET_ACCESS_KEY'] }}
